### ISSUE TITLE
F5 reload spends 2 requests available

### ISSUE THREAD

**Issue by pepetorres1998** [iksaku/uanl-repo-search#14]
I don't know if it is the expected behaviour or a bug.

Before F5:
<img width="1280" alt="imagen" src="https://user-images.githubusercontent.com/36722374/102800791-f9717c00-4379-11eb-9d00-6f9f30b7b93d.png">

After F5:
<img width="1280" alt="imagen" src="https://user-images.githubusercontent.com/36722374/102800856-127a2d00-437a-11eb-957f-628d6823d2ef.png">

**Comment by iksaku** [comment]
Sadly this is **expected** behavior at the moment.

Each time you load, reload or update the search parameters, one request is sent to GitHub’s API.

The best we could do is to only spend 1 request to fetch the repository list on load/reload, but due to the way that stats need to be fetched, we need to spend a second request initially.

I’m looking for a way to “cache” these stats at build time and keep them static for upcoming requests, this way, we could fire an update weekly and have decent update time, however, there’s no easy way ATM for this.

Will keep this open, I’m thinking on making the necessary changes for static first loads when Nuxt v3 is released.

Thanks for the heads up!

**Comment by iksaku** [comment]
Quick follow up... It seems that I misconfigured the project... I was hoping to provide a full static (`target: 'static'`) page for initial load, however, the build is serving an SPA...

[According to NuxtJS Docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-ssr), the `ssr` config flag prepares the project to be either rendered by a server or by the client entirely.
 - If set to `false` (current value), the project will be configured to render entirely by the client as a SPA, ignoring the `target: 'static'` configuration if not enforced by a plugin (Like a markdown renderer or something).
 - If set to `true` (going to set this), the project will be configured to render by a server.
   - If `ssr: true` and `target: 'static'`, then the project will be completely rendered at build time, publishing pure HTML and CSS for static content, and injecting payload for dynamic content (smart!)
   - If `ssr: true` and `target: 'server'`, then the project will be published as a runtime to execute using NodeJS on a server and render each page on the server whenever a request is received.

So, we are already expecting `target: 'static'`, now the thing is to configure `ssr: true` and expect full static payloads :tada:.

**Comment by pepetorres1998** [comment]
I was looking for something simple to contribute 😅 , do you have something on your mind?

**Comment by iksaku** [comment]
I have some ideas locally. If you’re free tonight we could spin up a simple pair programming session to further discuss what I got in mind.

PS: Here are my thoughts:
  - Extract main logic into hooks.
  - Make use of Nuxt’s Static helpers to generate data for first load.
  - Read static data from components and setup hooks once rendered on client.

**Comment by pepetorres1998** [comment]
This week I have tons of pending job, what about next week? 😄

**Comment by iksaku** [comment]
Sure thing, I’ll keep trying out, maybe push tonight a new branch with experimental changes
